name: Build, Run and Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Run and Test
    runs-on: self-hosted
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Enter app repo
        run: cd backend;

      - name: Build app
        run: dotnet build;

      - name: Run unit tests
        run: cd tests; dotnet test; cd ..

      - name: Run app
        run: cd src\Api; Start-Process dotnet -ArgumentList "run"; cd ..\..

      - name: Leave app repo
        run: cd ..

      - name: Checkout API test repo
        uses: actions/checkout@v4
        with:
          path: api-tests
          ref: master
          repository: fsouza99/guess-game-backend-testing
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run API tests
        run: cd api-tests; pytest; cd ..