name: Build, Run and Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Run and Test
    runs-on: self-hosted
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Build app
        run: dotnet build backend\App.sln

      - name: Checkout unit tests repo
        uses: actions/checkout@v4
        with:
          path: unit-tests
          ref: master
          repository: fsouza99/guess-game-backend-unit-testing
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run unit tests
        run: cd unit-tests; dotnet test; cd ..

      - name: Run app
        run: Start-Process dotnet -ArgumentList "run", "--project", "backend\src\Api"

      - name: Checkout API test repo
        uses: actions/checkout@v4
        with:
          path: integration-tests
          ref: master
          repository: fsouza99/guess-game-backend-testing
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run API tests
        run: cd integration-tests; pytest; cd ..